apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: quiz-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
REACT_APP_API_URL=http://backend-login-service:3001
