apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: quiz-frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080  # Example NodePort
  type: NodePort
